apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-keras-gpu
  labels:
    env: gpu-test
spec:
  containers:
  - name: tensorflow-keras-gpu
    image: afritzler/tensorflow-keras-gpu
    imagePullPolicy: IfNotPresent
  nodeSelector:
    gpu: "true"
