apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-keras-gpu
  labels:
    env: gpu-test
spec:
  containers:
  - name: tensorflow-keras-gpu
    image: afritzler/tensorflow-keras-gpu
    resources:
      limits:
        alpha.kubernetes.io/nvidia-gpu: 1
  nodeSelector:
    gpu: "true"
